{{ range $idx, $node := $.Values.nodes }}
---
apiVersion: v1
kind: Service
metadata:
  name: in3-node-{{ $.Values.chainName }}-{{ $idx }}
  labels:
    chain: {{ $.Values.chainName }}
spec:
  type: NodePort
  selector:           # Will select any pod with the below labels and become their svc
    app: in3-node
    chain: {{ $.Values.chainName }}
    node: {{ $node.name }}
  ports:
    - protocol: TCP
      port: 8500
      nodePort: {{ $node.nodePort }}
{{- end }}
