type: kubernetes.io/dockerconfigjson
kind: Secret
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuc2xvY2suaXQiOnsidXNlcm5hbWUiOiJtci5tZWVzZWVrcyIsInBhc3N3b3JkIjoiMk5rX1I0d0R6d3pwY21RWHF4WksiLCJhdXRoIjoiYlhJdWJXVmxjMlZsYTNNNk1rNXJYMUkwZDBSNmQzcHdZMjFSV0hGNFdrcz0ifX19
metadata:
  name: gitlab-image-secret

